name: Build PR
on:
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-ubunut:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7.28.0
      - name: Install dependencies
        run: pnpm i
      - name: Build project
        run: pnpm build
  build-wombat:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7.28.0
      - name: Install dependencies
        run: pnpm i
      - name: Build project
        run: pnpm build
  build-marcos:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7.28.0
      - name: Install dependencies
        run: pnpm i
      - name: Build project
        run: pnpm build