version: '3.8'

services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:3000:80" # Change this to just 3000:80 to bind on all interfaces on port 3000.
